# Generated by Django 3.1.1 on 2020-10-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_auto_20201001_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slidername', models.CharField(max_length=50, verbose_name='slidername')),
                ('image', models.ImageField(upload_to='slider')),
            ],
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_no',
            field=models.CharField(default='TRANS-2020-CF9E0E', editable=False, max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Transaction No'),
        ),
    ]
