# Generated by Django 3.1.1 on 2020-10-21 19:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_auto_20201019_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.TextField(default=django.utils.timezone.now, max_length=50, verbose_name='Size'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_no',
            field=models.CharField(default='TRANS-2020-EF587B', editable=False, max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Transaction No'),
        ),
        migrations.CreateModel(
            name='TestCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.products', verbose_name='Item')),
            ],
        ),
    ]
