# Generated by Django 3.1.1 on 2020-10-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_auto_20201022_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_no',
            field=models.CharField(default='TRANS-2020-671BCA', editable=False, max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Transaction No'),
        ),
    ]
